"""
pdf_generator.py — Branded PDF report builder for Outlaw Legal AI
-----------------------------------------------------------------
Creates a simple, professional PDF showing the analysis results.
"""

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from datetime import datetime
from pathlib import Path
import os
import logging
from typing import Dict, Any
from textwrap import wrap

logger = logging.getLogger("outlaw.pdf")

# ============================================================
# CONFIGURATION — BRANDING SETTINGS
# ============================================================

BRANDING = {
    "firm_name": "Outlaw Legal AI",
    "tagline": "Your Data-Driven Legal Strategy Partner",
    "website": "https://outlaw-legal.ai",
    "logo_path": "assets/outlaw_logo.png",
    "footer_note": "Generated by Outlaw Legal AI © 2025 — Confidential Report",
    "accent_color": colors.HexColor("#0D3B66"),
}


# ============================================================
# DRAWING HELPERS
# ============================================================

# Cache the resolved logo path at module level to avoid repeated path resolution
_LOGO_PATH = Path(__file__).resolve().parent / BRANDING["logo_path"]
_LOGO_EXISTS = _LOGO_PATH.exists()
# Pre-load logo image reader if logo exists for better performance
_LOGO_IMAGE = None
if _LOGO_EXISTS:
    try:
        _LOGO_IMAGE = ImageReader(str(_LOGO_PATH))
    except Exception as e:
        logger.warning(f"Could not load logo at startup: {e}")
        _LOGO_IMAGE = None


def _draw_header(pdf_canvas: canvas.Canvas, width: float, height: float):
    accent = BRANDING["accent_color"]
    pdf_canvas.setFillColor(accent)
    pdf_canvas.rect(0, height - 1.0 * inch, width, 1.0 * inch, fill=True, stroke=False)
    pdf_canvas.setFillColor(colors.white)
    pdf_canvas.setFont("Helvetica-Bold", 16)
    pdf_canvas.drawString(1 * inch, height - 0.75 * inch, BRANDING["firm_name"])
    pdf_canvas.setFont("Helvetica", 10)
    pdf_canvas.drawString(1 * inch, height - 0.95 * inch, BRANDING["tagline"])

    # Draw logo if available (using cached image reader)
    if _LOGO_IMAGE is not None:
        try:
            pdf_canvas.drawImage(_LOGO_IMAGE, width - 1.5 * inch, height - 0.95 * inch,
                        width=1.1 * inch, height=0.7 * inch, mask="auto")
        except Exception as e:
            logger.warning(f"Could not draw logo: {e}")

    pdf_canvas.setFillColor(colors.black)


def _draw_footer(pdf_canvas: canvas.Canvas, width: float):
    pdf_canvas.setFont("Helvetica-Oblique", 9)
    pdf_canvas.setFillColor(colors.grey)
    pdf_canvas.drawString(1 * inch, 0.7 * inch, BRANDING["footer_note"])
    pdf_canvas.drawRightString(width - 0.5 * inch, 0.7 * inch, f"Page {pdf_canvas.getPageNumber()}")
    pdf_canvas.setFillColor(colors.black)


def _draw_section(pdf_canvas: canvas.Canvas, title: str, y_position: float) -> float:
    pdf_canvas.setFont("Helvetica-Bold", 13)
    pdf_canvas.setFillColor(BRANDING["accent_color"])
    pdf_canvas.drawString(1 * inch, y_position, title)
    pdf_canvas.setFillColor(colors.black)
    return y_position - 18


def _draw_paragraph(pdf_canvas: canvas.Canvas, text: str, y_position: float, max_width=500, line_height=14) -> float:
    lines = wrap(text, width=int(max_width / 7))
    for line in lines:
        if y_position < 1 * inch:
            pdf_canvas.showPage()
            _draw_header(pdf_canvas, *LETTER)
            y_position = LETTER[1] - 1.5 * inch
        pdf_canvas.setFont("Helvetica", 11)
        pdf_canvas.drawString(1 * inch, y_position, line)
        y_position -= line_height
    return y_position - 6


# ============================================================
# MAIN GENERATOR
# ============================================================

def generate_pdf_report(data: Dict[str, Any], output_path: str) -> str:
    """Generate a simple multi-section PDF from analysis data."""
    logger.info(f"Generating PDF report → {output_path}")
    pdf_canvas = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER

    _draw_header(pdf_canvas, width, height)
    y_position = height - 1.4 * inch

    # Title section
    pdf_canvas.setFont("Helvetica-Bold", 14)
    pdf_canvas.drawString(1 * inch, y_position, "Legal Support Analysis Report")
    y_position -= 25
    pdf_canvas.setFont("Helvetica", 11)
    pdf_canvas.drawString(1 * inch, y_position, f"Jurisdiction: {data.get('jurisdiction','')}")
    y_position -= 14
    pdf_canvas.drawString(1 * inch, y_position, f"County: {data.get('county','')}")
    y_position -= 14
    pdf_canvas.drawString(1 * inch, y_position, f"Generated: {datetime.now():%Y-%m-%d %H:%M}")
    y_position -= 25

    # Facts
    y_position = _draw_section(pdf_canvas, "Facts", y_position)
    y_position = _draw_paragraph(pdf_canvas, data.get("facts", ""), y_position)

    # Statutes
    y_position = _draw_section(pdf_canvas, "Statutes", y_position)
    for statute in data.get("statutes", []):
        y_position = _draw_paragraph(pdf_canvas, f"{statute.get('citation', '')} — {statute.get('title', '')}", y_position)
        y_position = _draw_paragraph(pdf_canvas, statute.get("summary", ""), y_position)

    # Procedures
    y_position = _draw_section(pdf_canvas, "Procedures", y_position)
    for procedure in data.get("procedures", []):
        y_position = _draw_paragraph(pdf_canvas, f"• {procedure.get('name', '')}: {procedure.get('description', '')}", y_position)

    # Risks
    y_position = _draw_section(pdf_canvas, "Risks", y_position)
    for risk in data.get("risks", []):
        y_position = _draw_paragraph(pdf_canvas, f"[{risk.get('severity', '').upper()}] {risk.get('description', '')}", y_position)
        y_position = _draw_paragraph(pdf_canvas, f"→ Mitigation: {risk.get('mitigation', '')}", y_position)

    # Score
    y_position = _draw_section(pdf_canvas, "Winning Factor", y_position)
    score_data = data.get("score", {})
    y_position = _draw_paragraph(pdf_canvas, f"Overall Score: {score_data.get('overall', '')}", y_position)
    y_position = _draw_paragraph(pdf_canvas, f"Element Coverage: {score_data.get('element_score', '')}", y_position)
    y_position = _draw_paragraph(pdf_canvas, f"Evidence Strength: {score_data.get('evidence_score', '')}", y_position)
    y_position = _draw_paragraph(pdf_canvas, f"Narrative Clarity: {score_data.get('clarity_score', '')}", y_position)
    y_position = _draw_paragraph(pdf_canvas, f"Risk Penalty: {score_data.get('risk_penalty', '')}", y_position)

    _draw_footer(pdf_canvas, width)
    pdf_canvas.save()
    logger.info(f"PDF report saved successfully → {output_path}")
    return output_path
