"""
pdf_generator.py — Branded PDF report builder for Outlaw Legal AI
-----------------------------------------------------------------
Creates a simple, professional PDF showing the analysis results.
"""

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from datetime import datetime
from pathlib import Path
import os
import logging
from typing import Dict, Any
from textwrap import wrap

logger = logging.getLogger("outlaw.pdf")

# ============================================================
# CONFIGURATION — BRANDING SETTINGS
# ============================================================

BRANDING = {
    "firm_name": "Outlaw Legal AI",
    "tagline": "Your Data-Driven Legal Strategy Partner",
    "website": "https://outlaw-legal.ai",
    "logo_path": "assets/outlaw_logo.png",
    "footer_note": "Generated by Outlaw Legal AI © 2025 — Confidential Report",
    "accent_color": colors.HexColor("#0D3B66"),
}


# ============================================================
# DRAWING HELPERS
# ============================================================

def _draw_header(c: canvas.Canvas, width: float, height: float):
    accent = BRANDING["accent_color"]
    c.setFillColor(accent)
    c.rect(0, height - 1.0 * inch, width, 1.0 * inch, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 0.75 * inch, BRANDING["firm_name"])
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 0.95 * inch, BRANDING["tagline"])

    # Draw logo if available
    logo_path = Path(__file__).resolve().parent / BRANDING["logo_path"]
    if logo_path.exists():
        try:
            img = ImageReader(str(logo_path))
            c.drawImage(img, width - 1.5 * inch, height - 0.95 * inch,
                        width=1.1 * inch, height=0.7 * inch, mask="auto")
        except Exception as e:
            logger.warning(f"Could not draw logo: {e}")

    c.setFillColor(colors.black)


def _draw_footer(c: canvas.Canvas, width: float):
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawString(1 * inch, 0.7 * inch, BRANDING["footer_note"])
    c.drawRightString(width - 0.5 * inch, 0.7 * inch, f"Page {c.getPageNumber()}")
    c.setFillColor(colors.black)


def _draw_section(c: canvas.Canvas, title: str, y: float) -> float:
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(BRANDING["accent_color"])
    c.drawString(1 * inch, y, title)
    c.setFillColor(colors.black)
    return y - 18


def _draw_paragraph(c: canvas.Canvas, text: str, y: float, max_width=500, lh=14) -> float:
    lines = wrap(text, width=int(max_width / 7))
    for line in lines:
        if y < 1 * inch:
            c.showPage()
            _draw_header(c, *LETTER)
            y = LETTER[1] - 1.5 * inch
        c.setFont("Helvetica", 11)
        c.drawString(1 * inch, y, line)
        y -= lh
    return y - 6


# ============================================================
# MAIN GENERATOR
# ============================================================

def generate_pdf_report(data: Dict[str, Any], output_path: str) -> str:
    """Generate a simple multi-section PDF from analysis data."""
    logger.info(f"Generating PDF report → {output_path}")
    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER

    _draw_header(c, width, height)
    y = height - 1.4 * inch

    # Title section
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, y, "Legal Support Analysis Report")
    y -= 25
    c.setFont("Helvetica", 11)
    c.drawString(1 * inch, y, f"Jurisdiction: {data.get('jurisdiction','')}")
    y -= 14
    c.drawString(1 * inch, y, f"County: {data.get('county','')}")
    y -= 14
    c.drawString(1 * inch, y, f"Generated: {datetime.now():%Y-%m-%d %H:%M}")
    y -= 25

    # Facts
    y = _draw_section(c, "Facts", y)
    y = _draw_paragraph(c, data.get("facts", ""), y)

    # Statutes
    y = _draw_section(c, "Statutes", y)
    for s in data.get("statutes", []):
        y = _draw_paragraph(c, f"{s.get('citation', '')} — {s.get('title', '')}", y)
        y = _draw_paragraph(c, s.get("summary", ""), y)

    # Procedures
    y = _draw_section(c, "Procedures", y)
    for p in data.get("procedures", []):
        y = _draw_paragraph(c, f"• {p.get('name', '')}: {p.get('description', '')}", y)

    # Risks
    y = _draw_section(c, "Risks", y)
    for r in data.get("risks", []):
        y = _draw_paragraph(c, f"[{r.get('severity', '').upper()}] {r.get('description', '')}", y)
        y = _draw_paragraph(c, f"→ Mitigation: {r.get('mitigation', '')}", y)

    # Score
    y = _draw_section(c, "Winning Factor", y)
    sc = data.get("score", {})
    y = _draw_paragraph(c, f"Overall Score: {sc.get('overall', '')}", y)
    y = _draw_paragraph(c, f"Element Coverage: {sc.get('element_score', '')}", y)
    y = _draw_paragraph(c, f"Evidence Strength: {sc.get('evidence_score', '')}", y)
    y = _draw_paragraph(c, f"Narrative Clarity: {sc.get('clarity_score', '')}", y)
    y = _draw_paragraph(c, f"Risk Penalty: {sc.get('risk_penalty', '')}", y)

    _draw_footer(c, width)
    c.save()
    logger.info(f"PDF report saved successfully → {output_path}")
    return output_path
